// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw-Q7dmgZ3Dur48eseg__J8pw6CsOXCew',
    appId: '1:1057452569353:web:91778112e2b0d374f419d8',
    messagingSenderId: '1057452569353',
    projectId: 'evently-app-d2088',
    authDomain: 'evently-app-d2088.firebaseapp.com',
    storageBucket: 'evently-app-d2088.firebasestorage.app',
    measurementId: 'G-5882HJV1HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVtQzAm6kmO9zGTA8GT4hZr2_5qqHpiHg',
    appId: '1:1057452569353:android:70524c9eae007664f419d8',
    messagingSenderId: '1057452569353',
    projectId: 'evently-app-d2088',
    storageBucket: 'evently-app-d2088.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNTd7B9b6oBQxUQ2AFcQi47hPYhXXDojc',
    appId: '1:1057452569353:ios:966c4fbc9d6693caf419d8',
    messagingSenderId: '1057452569353',
    projectId: 'evently-app-d2088',
    storageBucket: 'evently-app-d2088.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNTd7B9b6oBQxUQ2AFcQi47hPYhXXDojc',
    appId: '1:1057452569353:ios:966c4fbc9d6693caf419d8',
    messagingSenderId: '1057452569353',
    projectId: 'evently-app-d2088',
    storageBucket: 'evently-app-d2088.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBw-Q7dmgZ3Dur48eseg__J8pw6CsOXCew',
    appId: '1:1057452569353:web:3ef210cb92ccf7a0f419d8',
    messagingSenderId: '1057452569353',
    projectId: 'evently-app-d2088',
    authDomain: 'evently-app-d2088.firebaseapp.com',
    storageBucket: 'evently-app-d2088.firebasestorage.app',
    measurementId: 'G-4ZB5CZQBYM',
  );

}